# Generated by Django 2.2.28 on 2024-03-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photoURL',
        ),
    ]
