# Generated by Django 2.2.28 on 2024-03-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_auto_20240304_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='hi', max_length=2000),
            preserve_default=False,
        ),
    ]
