# Generated by Django 2.2.28 on 2024-03-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_userprofile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cook_time',
            new_name='cook',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='prep_time',
            new_name='prep',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='no_of_saves',
            new_name='saves',
        ),
    ]
