# Generated by Django 2.2.28 on 2024-03-19 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_savedrecipes_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='star_count',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='star_submissions',
        ),
        migrations.AlterField(
            model_name='starredrecipes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='pantry.Recipe'),
        ),
    ]
