# Generated by Django 2.2.28 on 2024-03-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0003_userprofile_photourl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userID',
        ),
    ]
