# Generated by Django 2.2.28 on 2024-03-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0003_auto_20240309_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='date_pub',
            new_name='pub_date',
        ),
    ]
