# Generated by Django 2.2.28 on 2024-03-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0004_auto_20240309_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='saves',
            field=models.IntegerField(default=0),
        ),
    ]
